### ISSUE TITLE
Componente para usuário

### ISSUE THREAD

**Issue by isabellacgmsa** [GCES-SIGED/2022-1-SiGeD-Doc#3]
**Descrição**
Criar componente para pesquisar usuário

**Objetivo**
Fazer componente que aceite o input do nome usuário e botão que realize a requisição de acordo com o valor do input.

**Tarefas**

- [x]  Clear
- [x] Text field
- [x] Botão

**Checklist**
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [x] A issue possui labels.

**Comment by Liviarodrigues1** [comment]
Issue já havia sido resolvida, apenas foi confirmado sua função.
