### ISSUE TITLE
Frontend - Problema no cadastro de clientes

### ISSUE THREAD

**Issue by philipeserafim** [GCES-SIGED/2022-1-SiGeD-Doc#5]
Baseado na [#1](https://github.com/DITGO/2021-2-SiGeD-Doc/issues/1)

## História de usuário:

Eu, como usuário, desejo ter que seja feita a validação do CPF informado pelo usuário e que retorne a informação para que o usuário possa ter ciência que se trata de um CPF inválido, permitindo a correção.

## Critérios de aceitação

- [x] Permitir a retomada do fluxo de cadastro caso seja informado cpf inválido
- [x] Tratamento das informações quando for informado cpf inválido
- [x] Adequação com a resposta de validação do backend 

## Tarefas

- [x] Realizar validação do dado informado
- [x] Adicionar tratamento para cpf inválido

**Comment by PedroLimass** [comment]
MR referente a issue: [link](https://github.com/DITGO/2021-2-SiGeD-Frontend/pull/1)
