### ISSUE TITLE
Backend - Desativação de Cargos 

### ISSUE THREAD

**Issue by HenriqueAmorim20** [GCES-SIGED/2022-1-SiGeD-Doc#9]
**Descrição**
Baseada na https://github.com/DITGO/2021-2-SiGeD-Doc/issues/6

Funcionalidade de desativar no banco o cargo que não existe mais. 

**Tarefas**
- [x] Remodelar Banco
- [x] Alterar função de delete
- [x] Alterar rota

**Comment by giovannabbottino** [comment]
Marquei sem querer, foi mal.
